### ISSUE TITLE
送信ボタンを押下してから画面遷移するまでのラグ

### ISSUE THREAD

**Issue by nanikasi** [nanikasi/calljourney#63]
ボタンを押したときに、httpリクエストが返ってきていなくても、擬似的に成功とみなして、画面遷移する。
https://remix.run/docs/en/main/start/tutorial#optimistic-ui

OptimisticUIっていうらしい。こんなイメージ

**Comment by nagayamajun** [comment]
これ本当に問題ないかな？
個人的にはエラーが出た時に擬似的に画面遷移してしまうと送信したのにメールが返ってこないってなる気がしてる...

個人的には、
1. フロントエンドでエラーハンドリングしてエラーがあったら画面に表示する
2. リクエストを待っている間はbuttonをdisabledにして、loadingする
ほうがいい気している！

**Comment by nanikasi** [comment]
ありがとう！確かに！

> リクエストを待っている間はbuttonをdisabledにして、loadingする
ほうがいい気している！

こっちにしましょう！

**Comment by nagayamajun** [comment]
I will tackle this task by this weekend. 

in this task, i'll implement two tasks.
1 -> error handling
2 -> loading
3 -> button disabled

**Comment by nanikasi** [comment]
@nagayamajun 
Thanks!! I assigned you this task!
